---
title: "T-cell survival: 3 year dynamic"
author: "Anastasia Pavlova"
date: '2022-10-12'
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy.opts=list(width.cutoff=60),tidy=TRUE)
library(tidyverse)
library(ggplot2)
library(forcats)
library(broom)
library(ggbeeswarm)
library(data.table)
library(reshape2)
library(ggridges)
#!!! How to install brms, first we install 'V8' then the package itself
#Sys.setenv(DOWNLOAD_STATIC_LIBV8 = 1)
#install.packages(c("V8", "rstan", "brms"))
library(brms)
library(rstan)

rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())

get_os <- function(){
  sysinf <- Sys.info()
  if (!is.null(sysinf)){
  os <- sysinf['sysname']
  if (os == 'Darwin')
    os <- "osx"
  } else { ## mystery machine
    os <- .Platform$OS.type
    if (grepl("^darwin", R.version$os))
      os <- "osx"
    if (grepl("linux-gnu", R.version$os))
      os <- "linux"
  }
  tolower(os)
}
if (get_os() == "osx") {
  read_gz <- function(x) fread(paste("gzcat", x))
} else {
  read_gz <- function(x) fread(paste("zcat", x))
}

rename <- dplyr::rename
select <- dplyr::select
```

```{r message=FALSE, warning=FALSE}
setwd('/home/anpavlova/survival_new/3year')

data.raw.3y <- list.files("data", full.names = T) %>%
  as.list %>%
  lapply(function(x) read_delim(x) %>% mutate(sample.id = x)) %>%
  rbindlist

 # here we retain relevant columns and create new ones, extracting the sample characteristics from file names.

data.long.3y <-data.raw.3y %>% mutate(time.point = str_split(sample.id, "_", simplify = T)[, 2],
                                      time.point = as.numeric(gsub("\\..*","",time.point)),
                                sample.id = stringr::str_extract(sample.id, pattern = "(?<=data/)(.*?)(?=_)")) %>% 
  select(c('sample.id', 'time.point', 'count', 'cdr3nt', 'v', 'cdr3aa')) %>% 
  rename(clone.count = count, nt.seq = cdr3nt, aa.seq = cdr3aa)

head(data.long.3y)
  
```

```{r message=FALSE, warning=FALSE}

data.wide.3y <- data.long.3y %>% 
  pivot_wider(names_from = time.point, values_from = clone.count) %>% 
  rename(initial.rep = `2010`, subsequent.rep = `2013`) %>% 
  mutate(initial.quantile = case_when(
    is.na(initial.rep) ~ "Missing",
    initial.rep == 1 ~ "Singleton",
    initial.rep == 2 ~ "Doubleton",
    initial.rep == 3 ~ "Tripleton",
    initial.rep == 4 ~ "Quadrilton",
    initial.rep == 5 ~ "Quantilton",
    initial.rep == 6 ~ "Sixtilton",
    T ~ "Large"
    ))

###
data.wide.3y <- readRDS('/home/anpavlova/survival_new/3year/data.wide.3y.rds')

data.wide.3y %>%
  mutate(initial.rep = ifelse(is.na(initial.rep), 0, initial.rep)) %>%
  ggplot(aes(x = sample.id, 
             fill = initial.quantile %>% 
               fct_reorder(initial.rep))) +
  geom_bar() +
  scale_fill_brewer("Size", palette = "Spectral") +
  theme_classic() 

data.wide.3y %>% filter(initial.quantile != "Missing") %>% group_by(initial.quantile, sample.id) %>% 
     summarise(pre.rep = n())

data.wide.3y %>%
  filter(initial.quantile != "Missing") %>%
  ggplot(aes(x = initial.quantile, 
             fill = sample.id)) +
  geom_bar(position = "dodge") +
  scale_y_log10() +
  geom_hline(yintercept = 100, linetype = "dotted") +
  geom_hline(yintercept = 1000, linetype = "dashed") +
  theme_classic() +
  theme(legend.position = "bottom")

```

```{r message=FALSE, warning=FALSE, tidy=TRUE, tidy.opts=list(width.cutoff=60), fig.width = 5, fig.height=3}
# summarize & estimate parameters of beta distribution
alpha.prior <- 1
beta.prior <- 1
data.s.3y <- data.wide.3y %>%
  filter(initial.quantile != "Missing") %>%
  group_by(sample.id) %>%
  mutate(total.initial = sum(initial.rep, na.rm = T), # total = total number of detected bar codes (UMI)
        clones.initial = length(unique(aa.seq[!is.na(initial.rep)]))-1, # clones = clonal diversity, in other words number of  distinct clonotypes
        total.subsequent = sum(subsequent.rep, na.rm = T),
        clones.subsequent = length(unique(aa.seq[!is.na(subsequent.rep)]))-1) %>% 
  group_by(sample.id, initial.quantile) %>%
  mutate(clones.initial.quant = length(unique(aa.seq[!is.na(initial.rep)]))-1) %>%
  group_by(sample.id, initial.quantile, total.initial, clones.initial, total.subsequent, clones.subsequent, clones.initial.quant) %>%
  summarize(alpha = sum(!is.na(subsequent.rep)) + alpha.prior,
            beta = sum(is.na(subsequent.rep)) + beta.prior) %>%
  ungroup

###
data.abp.3y <- readRDS('/home/anpavlova/survival_new/3year/data.abp.3y.rds')

data.abp.3y <- data.s.3y %>%
  merge(tibble(p = c(0:10000/10000, 10^(-40000:-10000/10000)))) %>%
  group_by(sample.id, initial.quantile) %>%
  mutate(Pbeta = dbeta(p, alpha, beta)) %>%
  ungroup

data.abp.3y %>%
  group_by(sample.id) %>%
  mutate(height = Pbeta/ max(Pbeta)) %>%
  ggplot(aes(x = p, y = sample.id, height = height/3, 
             fill = factor(initial.quantile, levels = c("Singleton",
                                                      "Doubleton",
                                                      "Tripleton",
                                                      "Quadrilton",
                                                      "Quantilton",
                                                      "Large"))
  )) +
  geom_ridgeline(color = "NA", alpha = 0.9) +
  scale_color_cyclical(values = c("black", "white")) +
  scale_size_cyclical(values = c(2, 1)) +
  scale_x_log10("Capture probability", limits = c(0.5e-2, 9e-1)) + ylab("Pbeta") +
  scale_fill_brewer("", palette = "Spectral") +
  theme_classic() +
  theme(legend.position = "bottom")
```

```{r, fig.width = 8, fig.height=8}
data.abp.3y %>%
  group_by(sample.id) %>%
  mutate(height = Pbeta/ max(Pbeta)) %>%
  ggplot(aes(x = p, y = sample.id, height = height/3, 
             fill = factor(initial.quantile, levels = c("Singleton",
                                                      "Doubleton",
                                                      "Tripleton",
                                                      "Quadrilton",
                                                      "Quantilton",
                                                      "Sixtilton",
                                                      "Large"))
  )) +
  geom_ridgeline(color = "NA", alpha = 0.9) +
  scale_color_cyclical(values = c("black", "white")) +
  scale_size_cyclical(values = c(2, 1)) +
  scale_x_log10("Capture probability", limits = c(0.5e-2, 9e-1)) + ylab("Pbeta") +
  scale_fill_brewer("", palette = "Spectral") +
  theme_classic() +
  theme(legend.position = "bottom")
```

```{r}

data.abp.3y <- data.s.3y %>%
  merge(tibble(p = c(0:10000/10000, 10^(-40000:-10000/10000)))) %>%
  group_by(sample.id, initial.quantile) %>%
  mutate(Pbeta = dbeta(p, alpha, beta),
         meanbeta = alpha/(alpha+beta),
         sd2 = ((alpha*beta)/((alpha+beta)^2*(alpha+beta+1)))) %>%
  ungroup

#ab/((a+b)2(a+b+1))

data.abp.3y <- data.abp.3y %>% 
  group_by(sample.id, initial.quantile) %>%
  mutate(height = Pbeta/ max(Pbeta),
         median_prob = median(meanbeta))

ggplot() +
  geom_segment(data = data.abp.3y, aes(x = meanbeta, xend = meanbeta, y = as.numeric(factor(sample.id)), yend = as.numeric(factor(sample.id)) + .9, colour = factor(sample.id, levels = c("Str",
                                                      "Sch"))), size=1.7) +
  scale_x_log10("Capture probability", limits = c(0.9e-2, 9e-1)) + ylab("Pbeta") +
  scale_colour_brewer("", palette = "Spectral") +
  #facet_grid(factor(pre.point, levels = c('-7', '0', '7', '15'))~factor(time.point, levels = c('0', '7', '15', '45')), scales = "free_y") +
  theme_classic() +
  theme(legend.position = "bottom")

ggplot() +
  geom_point(data = data.abp.3y, aes(x = factor(initial.quintile), y = median_prob, colour = factor(sample.id, levels = c("Str",
                                                      "Sch"))), size=1.7) +
  #scale_x_log10("Capture probability", limits = c(0.9e-2, 9e-1)) + ylab("Pbeta") +
  scale_colour_brewer("", palette = "Spectral") +
  #facet_grid(factor(pre.point, levels = c('-7', '0', '7', '15'))~factor(time.point, levels = c('0', '7', '15', '45')), scales = "free_y") +
  theme_classic() +
  theme(legend.position = "bottom")

ggplot() + 
geom_pointrange(data=data.abp.3y, mapping=aes(x=factor(data.abp.3y$initial.quantile, levels = c("Singleton",
                                                      "Doubleton",
                                                      "Tripleton",
                                                      "Quadrilton",
                                                      "Quantilton",
                                                      "Sixtilton",
                                                      "Large")), y=as.numeric(data.abp.3y$meanbeta), ymin=(as.numeric(data.abp.3y$meanbeta) - as.numeric(data.abp.3y$sd2)), ymax=(as.numeric(data.abp.3y$meanbeta) + as.numeric(data.abp.3y$sd2)), color = factor(data.abp.3y$sample.id, levels = c("Str","Sch"))), width = 0.2) +
  scale_y_log10("Pbeta", limits = c(0.9e-2, 9e-1)) + 
  ylab("Pbeta") +
  #scale_colour_brewer("", palette = "Spectral") +
  scale_color_manual(name = "Sample", values = c("#D53E4F", "#66C2A5"), labels = c("47 y/o", "27 y/o")) +
  #facet_grid(factor(pre.point, levels = c('-7', '0', '7', '15'))~factor(time.point, levels = c('0', '7', '15', '45')), scales = "free_y") +
  theme_classic() +
  theme(legend.position = "bottom")
+ geom_point(data = tibble(x = 1:7, y = 1 - exp(-x)), aes(x = x, y = y), color = "black")
```


```{r, fig.width=8, fig.height=8, message=FALSE, warning=FALSE}

data.s.3y %>%
  ggplot(aes(x = clones.subsequent / clones.initial, y = alpha / (alpha + beta), 
             group = paste(initial.quantile), 
             color = factor(initial.quantile, levels = c("Singleton",
                                                       "Doubleton",
                                                       "Tripleton",
                                                       "Large")))) +
  geom_smooth(method = "lm", aes(), size = 1) +
  geom_point(size = 5) +
  geom_text(aes(label = sample.id), size = 2, color = "white") +
  scale_x_log10("Clones in 1st year / clones in 3th year") + 
  scale_y_log10("Capture probability") +
  scale_color_brewer("", palette = "Spectral") +
  theme_classic() +
  theme(aspect = 1, legend.position = "bottom")
```




```{r}
data.coord.3y <- data.s.3y %>%
  group_by(initial.quantile) %>%
  mutate(logRecaptureProb = log(alpha / (alpha + beta)), 
         logClonesSubsequent = log(clones.subsequent),
         logClonesInitial = log(clones.initial)) %>%
  ungroup %>%
  mutate(initial.quantile = factor(initial.quantile, levels = c("Singleton",
                                                       "Doubleton",
                                                       "Tripleton",
                                                       "Large")))
```

```{r}
data.coord.3y %>%
  ungroup %>%
  mutate(initial.quantile = as.factor(initial.quantile)) %>%
  do(lm(.$logRecaptureProb ~ .$initial.quantile + .$logClonesSubsequent + .$logClonesInitial) %>% tidy)
```

```{r}
data.coord.3y %>%
  ungroup %>%
  mutate(initial.quantile = as.factor(initial.quantile)) %>%
  do(lm(.$logRecaptureProb ~ .$initial.quantile + .$logClonesSubsequent + .$logClonesInitial) %>% aov %>% tidy) %>%
  mutate(var.explained.pct = sumsq / sum(sumsq) * 100) 
```

```{r, fig.width=8, fig.height=8}
data.wide.3y %>%
  mutate(initial.quantile = factor(initial.quantile, levels = c("Singleton",
                                                       "Doubleton",
                                                       "Tripleton",
                                                       "Large"))) %>%
  filter(!is.na(subsequent.rep)) %>%
  group_by(sample.id) %>%
  mutate(rank = rank(-subsequent.rep, ties.method	= "first"),
         freq.rec = subsequent.rep / sum(subsequent.rep)) %>%
  filter(initial.quantile != "Missing") %>%
  ggplot(aes(x = initial.quantile, y = rank)) +
  geom_hline(yintercept = 100, linetype = "dashed") +
  geom_quasirandom(aes(size = freq.rec, color = initial.quantile)) +
  geom_boxplot(fill = NA, color = "black", outlier.colour = NA) +
  coord_flip() +
  scale_y_log10("Clonotype rank") +
  xlab("") +
  scale_size_continuous("Clonotype size") +
  scale_color_brewer("", palette = "Spectral") +
  facet_wrap(.~sample.id, scales = "free_x") +
  theme_classic() +
  theme(aspect = 1, legend.position = "bottom")
```